### ISSUE TITLE
go get error

### ISSUE THREAD

**Issue by lhwcd** [taosdata/driver-go#1]
➜  tdengine-test git:(master) ✗ go get github.com/taosdata/TDengine/src/connector/go/src/taosSql 
go: found github.com/taosdata/TDengine/src/connector/go/src/taosSql in github.com/taosdata/TDengine v0.0.0-20200303093529-58efbd6b99fe
# github.com/taosdata/TDengine/src/connector/go/src/taosSql
../../../pkg/mod/github.com/taosdata/!t!dengine@v0.0.0-20200303093529-58efbd6b99fe/src/connector/go/src/taosSql/result.go:23:10: fatal error: 'taos.h' file not found
#include <taos.h>
         ^~~~~~~~
1 error generated.

**Comment by localvar** [comment]
please install TDengine (only install client is fine) then try again.

**Comment by MadeInChina** [comment]
+1, is that possible to provide a docker image as builder to build driver-go?
