### ISSUE TITLE
用go一次执行多个sql，scan只能出一个结果，该如何解析

### ISSUE THREAD

**Issue by baoyou02** [taosdata/driver-go#100]
`
select * from 表1；
select * from 表2；
select * from 表3；
`
我这样执行多条sql，shell 能出多个结果：
![image](https://user-images.githubusercontent.com/108656378/179474349-06271f97-ded4-4689-95e1-990b12c9e999.png)
但 scan 这样只能弄出一条
![image](https://user-images.githubusercontent.com/108656378/179474391-006f33a7-8fe6-405a-8732-3dfb82e162a1.png)
![image](https://user-images.githubusercontent.com/108656378/179474459-4db6b44e-97b6-4376-ad22-f78de9264cda.png)
请问该如何解析？ @sangshuduo

**Comment by baoyou02** [comment]
@huskar-t  golang 大佬，scan 支持这样吗

**Comment by huskar-t** [comment]
@baoyou02 多个查询不可以通过分号分割来进行一次 query。需要每个查询单独进行 query 后 scan

**Comment by baoyou02** [comment]
哦哦，感谢
