### ISSUE TITLE
taosdata / driver-go 版本升级后报错(2.0.0 -> 2.0.4)

### ISSUE THREAD

**Issue by fetaoily** [taosdata/driver-go#103]
1. Go   版本: go version go1.18.4 windows/amd64
2. 操作系统: Win11
3. 报错内容
`# github.com/taosdata/driver-go/v2/wrapper
D:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: $WORK\b251\_x009.o: in function `_cgo_e608cae81cef_Cfunc_taos_is_update_query':
/tmp/go-build/cgo-gcc-prolog:279: undefined reference to `taos_is_update_query'
D:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: $WORK\b251\_x009.o: in function `_cgo_e608cae81cef_Cfunc_taos_reset_current_db':
/tmp/go-build/cgo-gcc-prolog:387: undefined reference to `taos_reset_current_db'
collect2.exe: error: ld returned 1 exit status
error Command failed with exit code 2.`
![image](https://user-images.githubusercontent.com/501984/181149992-11aa6c39-2173-4bbe-9cfb-3fb5eeb34819.png)

**Comment by huskar-t** [comment]
@fetaoily TDengine 使用哪个版本

**Comment by fetaoily** [comment]
> @fetaoily TDengine 使用哪个版本

@huskar-t 
```
C:\TDengine>taos -V
version: 2.4.0.5
```

**Comment by huskar-t** [comment]
@fetaoily 此版本不完全包含 go-driver 2.0.4 所需方法，请升级 TDengine 或降低 go-driver version
