### ISSUE TITLE
go程循环执行查询时，一会就会报错 Unable to establish connection，time.Sleep(time.Millisecond * 300)这样控制速率才不会报错

### ISSUE THREAD

**Issue by zengbinghuan** [taosdata/driver-go#11]
func queryPage() {
	// go程标识
	tag := fmt.Sprintf("分页查询:%v-%v", time.Now().Nanosecond(), numb)
	wokerHum := worker{Tag: tag}
	goMap[tag] = wokerHum
	for i := 0; i < numb; i++ {

		go func() {
			db, _ := sql.Open("taosSql", "root:taosdata@tcp(127.0.0.1:6030)/newdb?charset=utf8&parseTime=true")
			defer db.Close()
			rnd := rand.New(rand.NewSource(time.Now().UnixNano()))
			for {

				paramStr := fmt.Sprintf("select * from humiture order by datetime desc limit 10 offset %v;", rnd.Int31n(1000000))

				now1 := time.Now()
				_, err := db.Query(paramStr)
				if err != nil {
					log.Println(err)

					time.Sleep(time.Millisecond * time.Duration(rnd.Int31n(1000)))

				}
				now2 := time.Now().Sub(now1)
				//fmt.Println(res)
				wokerHum.Delay = now2.Milliseconds()

				manageChan <- wokerHum
				//time.Sleep(time.Millisecond * 300)
				//time.Sleep(time.Millisecond * time.Duration(rnd.Int31n(1000)))

			}

		}()
	}
}

**Comment by zengbinghuan** [comment]
我执行插入语句就没有这个问题，也是这样的逻辑

**Comment by zengbinghuan** [comment]
查询允许一段时间就会报一下错误
![image](https://user-images.githubusercontent.com/38431710/94529246-10696c00-026c-11eb-866a-4d5e607e0690.png)
### 一下是完整代码
`package main

import (
	"bytes"
	"database/sql"
	"flag"
	"fmt"
	"io/ioutil"
	"log"
	"math/rand"
	"net/http"
	"net/url"
	"strings"
	"sync"
	"time"

	"github.com/gin-contrib/cors"
	"github.com/gin-gonic/gin"
	"github.com/gin-gonic/gin/binding"

	jsoniter "github.com/json-iterator/go"
	_ "github.com/taosdata/driver-go/taosSql"
)

var (
	// go程 map
	goMap = map[string]worker{}

	// go程控制管道
	manageChan = make(chan worker)

	locker = sync.Mutex{}

	addr     = ":8888"
	taskType = "tdengine"
	numb     = 1
)

type worker struct {
	Data      []byte
	Tag       string     //进程标识
	BeginTime *time.Time // 工作进程开始时间
	SendNum   int        //发送数量
	ErrNum    int        // 失败数量
	SendPer   float64    //发送速率
	Status    int        // 工作进程状态 0-工作中 1-停止
	Delay     int64
}

func init() {
	// 统计测试控制

	go manageHandle()

	go func() {
		time.Sleep(time.Second * 3)

		for {

			for _, worker := range goMap {
				// 数据打印
				if worker.BeginTime != nil {
					log.Println("***********************************")
					log.Println("工作进程：", worker.Tag, ",开始时间：", worker.BeginTime.Format("2006-01-02 15:04:05"))
					log.Println("发送情况：累计发送数据-", worker.SendNum, ",发送错误数量：", worker.ErrNum, ",平均发送（条数/每秒）：", int(worker.SendPer), ",实时延长(ms)：", worker.Delay)
				}

			}
			// 数据打印
			log.Printf("--------------------%v----------------------", taskType)
			time.Sleep(time.Second * 5)
		}

	}()

}

func main() {
	flag.StringVar(&taskType, "type", "tdengine", "输入tdengine,infludb")
	flag.IntVar(&numb, "numb", 1, "输入工作进程数")
	flag.Parse()
	log.SetFlags(log.Llongfile | log.LstdFlags)
	if taskType == "tdAdd" {
		addTask()
	} else if taskType == "inAdd" {
		addTaskInfludb()
	} else if taskType == "tdQuery" {
		queryPage()
	} else if taskType == "inQuery" {
		queryPageInfludb()
	}
	Router := initRouter() //注册路由
	log.Println("服务器开启")   // 日志测试代码
	//Router.RunTLS(":443","ssl.pem", "ssl.key")  // https支持 需要添加中间件
	s := &http.Server{
		Addr:           addr,
		Handler:        Router,
		ReadTimeout:    10 * time.Second,
		WriteTimeout:   10 * time.Second,
		MaxHeaderBytes: 1 << 20,
	}

	time.Sleep(10 * time.Microsecond)
	fmt.Printf(`
influx测试服务已开启:http://127.0.0.1%s

`, s.Addr)

	_ = s.ListenAndServe()

}

func initRouter() *gin.Engine {
	var Router = gin.Default()

	// 跨越配置
	Router.Use(cors.New(cors.Config{
		AllowOrigins:     []string{"*"},
		AllowMethods:     []string{"*"},
		AllowHeaders:     []string{"*"},
		AllowCredentials: true,
		MaxAge:           12 * time.Hour,
	}))

	// 添加温湿度测试任务
	Router.GET("/humiture/add", addHumiture)
	// 添加股票交易记录
	Router.GET("/humiture/many", addMany)
	// 添加温湿度测试任务
	Router.GET("/humiture/infludb/add", addHumitureInfludb)
	// 添加股票交易记录
	Router.GET("/humiture/infludb/many", addManyInfludb)
	return Router

}

type addHumitureReq struct {
	Host        string  `form:"host"`
	Temperature float64 `form:"temperature "`
	Humidity    float64 `form:"humidity"`
	Number      int     `form:"number"` // 监控点数
}

// manageHandle 测点管理
func manageHandle() {
	for worker := range manageChan {

		srcWorker := goMap[worker.Tag]
		if srcWorker.BeginTime == nil {
			now := time.Now()
			srcWorker.BeginTime = &now
		}

		// 计算统计
		resObj := resErr{}
		jsoniter.Unmarshal(worker.Data, &resObj)
		if resObj.ErrorStr != "" {
			srcWorker.ErrNum++

		} else {
			srcWorker.SendNum++
		}
		duration := time.Now().Sub(*srcWorker.BeginTime)
		srcWorker.SendPer = float64(srcWorker.SendNum) / duration.Seconds()
		srcWorker.Delay = worker.Delay
		goMap[worker.Tag] = srcWorker
	}

}

/*TDengine测试部分*/
var ()

// addHumiture 添加温湿度测试
func addHumiture(c *gin.Context) {
	req := addHumitureReq{
		Temperature: 200000,
		Humidity:    1000000,
		Number:      100,
	}
	BindQuery(c, &req)
	RespondFormat(c, 200, "", gin.H{"req": req})
	// 发送influxDb
	// go程标识
	tag := fmt.Sprintf("Humiture:%v-%v", time.Now().Nanosecond(), req.Number)
	wokerHum := worker{Tag: tag}
	goMap[tag] = wokerHum
	// 开启go程测点
	over := false
	for i := 0; i < req.Number; i++ {
		go func() {
			rnd := rand.New(rand.NewSource(time.Now().UnixNano()))
			for {
				if over {
					return
				}

				temp := req.Temperature * rnd.Float64()
				hum := req.Humidity * rnd.Float64()
				paramStr := fmt.Sprintf("insert into humiture values(NOW, '%v', %v, %v)", req.Host, temp, hum)
				//log.Println(paramStr)
				// res, err := Post("", paramStr, infludbWriteUrl)
				// if err != nil {
				// 	log.Println(err)
				// 	return
				// }
				// wokerHum.Data = res
				db, _ := sql.Open("taosSql", "root:taosdata@tcp(127.0.0.1:6030)/newdb?charset=utf8&parseTime=true")
				defer db.Close()
				_, err := db.Exec(paramStr)
				if err != nil {
					log.Println(err)
					return
				}
				//fmt.Println(res)

				manageChan <- wokerHum
				// time.Sleep(time.Millisecond * 1)
				time.Sleep(time.Millisecond * time.Duration(rnd.Int31n(1000)))

			}

		}()
	}
	// time.Sleep(time.Second)
	// over = true

}
func addTask() {
	req := addHumitureReq{
		Temperature: 200000,
		Humidity:    1000000,
		Number:      numb,
		Host:        "tdengine",
	}

	// 发送influxDb
	// go程标识
	tag := fmt.Sprintf("Humiture:%v-%v", time.Now().Nanosecond(), req.Number)
	wokerHum := worker{Tag: tag}
	goMap[tag] = wokerHum
	// 开启go程测点
	over := false
	for i := 0; i < req.Number; i++ {
		go func() {
			rnd := rand.New(rand.NewSource(time.Now().UnixNano()))
			db, err := sql.Open("taosSql", "root:taosdata@tcp(127.0.0.1:6030)/newdb?charset=utf8&parseTime=true")
			if err != nil {
				log.Fatal(err)
				return
			}
			for {
				if over {
					return
				}

				temp := req.Temperature * rnd.Float64()
				hum := req.Humidity * rnd.Float64()
				paramStr := fmt.Sprintf("insert into humiture values(NOW, '%v', %v, %v)", req.Host, temp, hum)

				now1 := time.Now()
				_, err = db.Exec(paramStr)
				if err != nil {
					log.Println(err)
					return
				}

				now2 := time.Now().Sub(now1)
				wokerHum.Delay = now2.Milliseconds()
				// /fmt.Println(wokerHum.Delay)
				manageChan <- wokerHum
				// time.Sleep(time.Millisecond * 1)
				//time.Sleep(time.Millisecond * time.Duration(rnd.Int31n(1000)))

			}

		}()
	}
}

// addMany 批量插入
func addMany(c *gin.Context) {
	req := addHumitureReq{}
	BindQuery(c, &req)
	RespondFormat(c, 200, "", gin.H{"req": req})
	// 发送influxDb
	// go程标识
	tag := fmt.Sprintf("Stock:%v-%v", time.Now().Nanosecond(), req.Number)
	wokerHum := worker{Tag: tag}
	goMap[tag] = wokerHum

	// 开启go程测点
	for i := 0; i < req.Number; i++ {
		go func() {
			db, _ := sql.Open("taosSql", "root:taosdata@tcp(127.0.0.1:6030)/newdb?charset=utf8&parseTime=true")
			defer db.Close()
			for {
				paramStr := sendMany(req, 20)

				_, err := db.Exec(paramStr)
				if err != nil {
					log.Println(err)
					return
				}
				//fmt.Println(res)
				manageChan <- wokerHum

				//time.Sleep(time.Millisecond * time.Duration(rnd.Int31n(1000)))

			}

		}()
	}
}

// query分页查询
func queryPage() {
	// go程标识
	tag := fmt.Sprintf("分页查询:%v-%v", time.Now().Nanosecond(), numb)
	wokerHum := worker{Tag: tag}
	goMap[tag] = wokerHum
	for i := 0; i < numb; i++ {
		go func() {
			db, _ := sql.Open("taosSql", "root:taosdata@tcp(127.0.0.1:6030)/newdb?charset=utf8&parseTime=true")
			defer db.Close()
			rnd := rand.New(rand.NewSource(time.Now().UnixNano()))
			for {
				paramStr := fmt.Sprintf("select * from humiture order by datetime desc limit 10 offset %v;", rnd.Int31n(1000000))
				now1 := time.Now()
				_, err := db.Query(paramStr)
				if err != nil {
					log.Println(err)
					time.Sleep(time.Millisecond * time.Duration(rnd.Int31n(1000)))
					continue
				}
				now2 := time.Now().Sub(now1)
				wokerHum.Delay = now2.Milliseconds()
				manageChan <- wokerHum
				if wokerHum.Delay > 300 {
					time.Sleep(time.Millisecond * 1000)
				}

			}

		}()
	}
}
func sendMany(req addHumitureReq, sum int) string {

	values := make([]string, 0, sum)
	for i := 0; i < sum; i++ {
		rnd := rand.New(rand.NewSource(time.Now().UnixNano()))
		temp := req.Temperature * rnd.Float64()
		hum := req.Humidity * rnd.Float64()
		value := fmt.Sprintf("(NOW, '%v', %v, %v)", req.Host, temp, hum)
		values = append(values, value)
	}
	value := strings.Join(values, " ")
	s := "insert into humiture values" + value + ";"
	return s

}

// infludb 测试部分

var (

	// influxDbUrl 地址
	infludbWriteUrl = "http://127.0.0.1:8086/write?db=newdb"
	infludbReadUrl  = "http://127.0.0.1:8086/query?pretty=true"
	client          = &http.Client{

		Timeout: time.Second * 30, //超时时间
	}
)

// resErr influx错误相应
type resErr struct {
	ErrorStr string `json:"error"`
}

// addHumiture 添加温湿度测试

func addHumitureInfludb(c *gin.Context) {
	req := addHumitureReq{
		Temperature: 200000,
		Humidity:    1000000,
		Number:      100,
	}
	BindQuery(c, &req)
	RespondFormat(c, 200, "", gin.H{"req": req})
	// 发送influxDb
	// go程标识
	tag := fmt.Sprintf("Humiture:%v-%v", time.Now().Nanosecond(), req.Number)
	wokerHum := worker{Tag: tag}
	goMap[tag] = wokerHum
	// 开启go程测点
	over := false
	var count int64
	for i := 0; i < req.Number; i++ {
		go func() {
			rnd := rand.New(rand.NewSource(time.Now().UnixNano()))
			for {
				if over {
					return
				}
				count++
				temp := req.Temperature * rnd.Float64()
				hum := req.Humidity * rnd.Float64()
				paramStr := fmt.Sprintf("humiture,host=%v temp=%v,hum=%v %v", req.Host, temp, hum, time.Now().UnixNano()+count)
				res, err := Post("", paramStr, infludbWriteUrl)
				if err != nil {
					log.Println(err)
					return
				}
				wokerHum.Data = res

				manageChan <- wokerHum

				//time.Sleep(time.Millisecond * time.Duration(rnd.Int31n(1000)))

			}

		}()
	}
	// time.Sleep(time.Second)
	// over = true
}
func addTaskInfludb() {
	req := addHumitureReq{
		Temperature: 200000,
		Humidity:    1000000,
		Number:      numb,
		Host:        "infludb",
	}

	// 发送influxDb
	// go程标识
	tag := fmt.Sprintf("Humiture:%v-%v", time.Now().Nanosecond(), req.Number)
	wokerHum := worker{Tag: tag}
	goMap[tag] = wokerHum
	// 开启go程测点
	over := false
	var count int64
	for i := 0; i < req.Number; i++ {
		go func() {
			rnd := rand.New(rand.NewSource(time.Now().UnixNano()))
			for {
				if over {
					return
				}
				count++
				temp := req.Temperature * rnd.Float64()
				hum := req.Humidity * rnd.Float64()
				paramStr := fmt.Sprintf("humiture,host=%v temp=%v,hum=%v %v", req.Host, temp, hum, time.Now().UnixNano()+count)
				now1 := time.Now()
				res, err := Post("", paramStr, infludbWriteUrl)
				if err != nil {
					log.Println(err)
					return
				}
				wokerHum.Data = res
				now2 := time.Now().Sub(now1)

				wokerHum.Delay = now2.Milliseconds()
				wokerHum.Data = res

				manageChan <- wokerHum

				//time.Sleep(time.Millisecond * time.Duration(rnd.Int31n(1000)))

			}

		}()
	}
	// time.Sleep(time.Second)
	// over = true
}

// query分页查询
func queryPageInfludb() {
	req := addHumitureReq{
		Temperature: 200000,
		Humidity:    1000000,
		Number:      numb,
		Host:        "infludb",
	}

	// 发送influxDb
	// go程标识
	tag := fmt.Sprintf("Humiture:%v-%v", time.Now().Nanosecond(), req.Number)
	wokerHum := worker{Tag: tag}
	goMap[tag] = wokerHum
	// 开启go程测点

	for i := 0; i < req.Number; i++ {
		go func() {
			rnd := rand.New(rand.NewSource(time.Now().UnixNano()))
			for {

				paramStr := fmt.Sprintf(`db=newdb&q=select * from humiture order by time desc limit 10 offset %v`, rnd.Int31n(1000000))
				now1 := time.Now()
				res, err := PostForm("", paramStr, infludbReadUrl)
				if err != nil {
					log.Println(err)
					return
				}
				now2 := time.Now().Sub(now1)
				//fmt.Println(string(res))
				wokerHum.Delay = now2.Milliseconds()
				wokerHum.Data = res

				manageChan <- wokerHum

				//time.Sleep(time.Millisecond * time.Duration(rnd.Int31n(1000)))

			}

		}()
	}
}

// addMany 批量插入
func addManyInfludb(c *gin.Context) {
	req := addHumitureReq{}
	BindQuery(c, &req)
	RespondFormat(c, 200, "", gin.H{"req": req})
	// 发送influxDb
	// go程标识
	tag := fmt.Sprintf("Stock:%v-%v", time.Now().Nanosecond(), req.Number)
	wokerHum := worker{Tag: tag}
	goMap[tag] = wokerHum
	// 开启go程测点
	for i := 0; i < req.Number; i++ {
		go func() {

			for {
				paramStr := sendMany(req, 20)

				res, err := Post("", paramStr, infludbWriteUrl)
				if err != nil {
					log.Println(err)
					return
				}
				wokerHum.Data = res

				manageChan <- wokerHum

				//time.Sleep(time.Millisecond * time.Duration(rnd.Int31n(1000)))

			}

		}()
	}

}

func sendManyInfludb(req addHumitureReq, sum int) string {
	paramStr := ""
	var count int64
	for i := 0; i < sum; i++ {
		count++
		rnd := rand.New(rand.NewSource(time.Now().UnixNano()))
		temp := req.Temperature * rnd.Float64()
		hum := req.Humidity * rnd.Float64()
		paramStr += fmt.Sprintf(`humiture,host=%v temp=%v,hum=%v %v
		`, req.Host, temp, hum, time.Now().UnixNano()+count)

	}

	return paramStr
}

//Post 发送Post请求
func Post(headerStr, paramStr, wxUrl string) (b []byte, err error) {

	request, _ := http.NewRequest("POST", wxUrl, bytes.NewBuffer([]byte(paramStr)))
	//设置请求头部
	if headerStr != "" {
		header, err := url.ParseQuery(headerStr)
		if err == nil {
			for key, val := range header {

				for _, v := range val {
					request.Header.Set(key, v)
				}

			}
		}

	}

	request.Header.Set("Content-Type", "application/x-www-form-urlencoded")
	// request.Header.Set("User-Agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36")
	//request.ParseForm()
	res, err := client.Do(request)

	body := []byte{}
	if err != nil {
		return body, err
		//return
	} else {
		defer res.Body.Close()
		body, err = ioutil.ReadAll(res.Body)
	}

	return body, err

}

//发送Get请求
func PostForm(headerStr, paramStr, wxUrl string) (b []byte, err error) {

	request, _ := http.NewRequest("POST", wxUrl, bytes.NewBuffer([]byte(paramStr)))
	//设置请求头部
	if headerStr != "" {
		header, err := url.ParseQuery(headerStr)
		if err == nil {
			for key, val := range header {

				for _, v := range val {
					request.Header.Set(key, v)
				}

			}
		}

	}
	request.PostForm, _ = url.ParseQuery(paramStr)

	request.Header.Set("Content-Type", "application/x-www-form-urlencoded")
	// request.Header.Set("User-Agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36")
	request.ParseForm()
	res, err := client.Do(request)

	body := []byte{}
	if err != nil {
		return body, err
		//return
	} else {
		defer res.Body.Close()
		body, err = ioutil.ReadAll(res.Body)
	}

	return body, err

}

// Unmarshal 反序列化接口
func Unmarshal(ctx *gin.Context, target interface{}) error {
	body, err := ioutil.ReadAll(ctx.Request.Body)
	if err != nil {
		return err
	}
	err = jsoniter.Unmarshal(body, target)
	if err != nil {
		return err
	}
	err = binding.Validator.ValidateStruct(target)
	if err != nil {
		return err
	}
	return nil
}

// BindQuery 反序列化接口
func BindQuery(ctx *gin.Context, target interface{}) error {

	err := ctx.BindQuery(target)
	if err != nil {
		return err
	}
	err = binding.Validator.ValidateStruct(target)
	if err != nil {
		return err
	}
	return nil
}

// RespondFormat 统一响应接口
func RespondFormat(c *gin.Context, status int, msg string, json gin.H) {

	c.JSON(http.StatusOK, gin.H{
		"status": status,
		"msg":    msg,
		"data":   json,
	})

}
`

**Comment by zengbinghuan** [comment]
这个是运行查询的命令 go run td.go -type tdQuery -numb 1

**Comment by zengbinghuan** [comment]
解决了，查询的rows不需要也要把他close。
![image](https://user-images.githubusercontent.com/38431710/94538179-44498f00-0276-11eb-99ab-a19e957f9817.png)

**Comment by fly-studio** [comment]
Markdown 谢谢
