### ISSUE TITLE
表中插入字符串时报语法错误

### ISSUE THREAD

**Issue by bluceyee** [taosdata/driver-go#115]
往数据库中插入字符串的时候，如果不在字符串上手动使用''包裹，会报语法错误。

测试步骤如下 ：
如果有一张有表
create TABLE if not exists test(ts timestamp,
                                               testValue VARCHAR(120)
);
	

Exec("insert into test(ts,testValue) values(?,?)", "2022-08-17 09:23:09.978", "xyzaaaaaaaaaa")
驱动common.InterpolateParams(query, args) 解析后的sql语句为
insert into test(ts,testValue) values(2022-08-17 09:23:09.978,xyzaaaaaaaaaa)
执行报警，原因是字符串没有加引号
[0x216] syntax error near '2022-08-17 09:23:09.978,xyzaaaaaaaaaa)' (invalid timestamp), insert into test(ts,testValue) values('2022-08-17 09:23:09.978','xyzaaaaaaaaaa')

Exec("insert into test(ts,testValue) values(?,?)", **"'**2022-08-17 09:23:09.978**'"**, "xyzaaaaaaaaaa")
驱动common.InterpolateParams(query, args) 解析后的sql语句为
insert into test(ts,testValue) values('2022-08-17 09:23:09.978',xyzaaaaaaaaaa)
[0x216] syntax error near 'xyzaaaaaaaaaa)' (invalid data or symbol), insert into test(ts,testValue) values('\'2022-08-17 09:23:09.978\'','xyzaaaaaaaaaa')

Exec("insert into test(ts,testValue) values(?,?)", "'2022-08-17 09:23:09.978'", "'xyzaaaaaaaaaa'")
驱动common.InterpolateParams(query, args) 解析后的sql语句为
insert into test(ts,testValue) values('2022-08-17 09:23:09.978','xyzaaaaaaaaaa')

会报sql语法错误，原因是“test” 在sql 拼接的时候，会拼成 insert into test(ts,value) values(2022-08-17 09:03:09.978, test);插入时报Error: [0x216] syntax error near '2022-08-17 09:23:09.978,'8-1000-16604792291907' (invalid timestamp)

Exec("insert into test(ts,testValue) values(?,?)", time.Now(), "'xyzaaaaaaaaaa'")
这种写法也没有问题

如果插入的字符串都要额外加 '' ， 显示不合适，看了mysql 的代码，他们是在字符串那自动补充了'', 建议修改成判断字符串，自动加一个''

tdegine 的处理
func InterpolateParams(query string, args []driver.Value) (string, error) {
....
		case time.Time:
			t := v.Format(time.RFC3339Nano)
			buf.WriteByte('\'')
			buf.WriteString(t)
			buf.WriteByte('\'')
		case []byte:
			buf.Write(v)
		case string:
			buf.WriteString(v)
		default:
			return "", driver.ErrSkip
		}
		if buf.Len() > MaxTaosSqlLen {
			return "", errors.New("sql statement exceeds the maximum length")
		}

mysql 的处理
func (mc *mysqlConn) interpolateParams(query string, args []driver.Value) (string, error) {
...
		case string:
			**buf = append(buf, '\'')**
			if mc.status&statusNoBackslashEscapes == 0 {
				buf = escapeStringBackslash(buf, v)
			} else {
				buf = escapeStringQuotes(buf, v)
			}
			**buf = append(buf, '\'')**
		default:
			return "", driver.ErrSkip
		}

**Comment by sangshuduo** [comment]
由于 TDengine 需要大量已经在使用之前处理方法的用户保持兼容，所以暂时不会支持自动添加引号。谢谢您的 issue 和建议。
