### ISSUE TITLE
按照 DEMO 通过 restful 方式操作 DB，直接报错。

### ISSUE THREAD

**Issue by ThreeAndTwo** [taosdata/driver-go#120]
`
package main

import (
	"database/sql"
	"fmt"
	"time"
	_ "github.com/taosdata/driver-go/v3/taosRestful"
)

func main() {
	var taosDSN = "root:taosdata@http(localhost:6041)/"
	taos, err := sql.Open("taosRestful", taosDSN)
	if err != nil {
		fmt.Println("failed to connect TDengine, err:", err)
		return
	}
	defer taos.Close()

	// taos.Exec("create database if not exists test")
	// taos.Exec("create table if not exists tb1 (ts timestamp, a int)")
	_, err = taos.Exec("insert into test.d0 values(NOW, 9.96000, 116, 0.32778)")
	if err != nil {
		fmt.Println("failed to insert, err:", err)
		return
	}

	rows, err := taos.Query("select * from test.d0 limit 10")
	if err != nil {
		fmt.Println("failed to select from table, err:", err)
		return
	}

	defer rows.Close()
	for rows.Next() {
		var r struct {
			Ts      time.Time
			Current float64
			Voltage int
			Phase   float64
		}
		err := rows.Scan(&r.Ts, &r.Current, &r.Voltage, &r.Phase)
		if err != nil {
			fmt.Println("scan error:\n", err)
			return
		}
		fmt.Println(r.Ts, r.Current)
	}
}
`
<img width="1926" alt="image" src="https://user-images.githubusercontent.com/35927054/192767691-bbd365ea-5478-4eec-8741-07ac26d2ad77.png">

**Comment by zitsen** [comment]
这个 demo 示例仅适用于 TDengine 3.0 ，如果使用 2.x 请参考 2.x 文档 https://docs.taosdata.com/2.6/
