### ISSUE TITLE
v3@v3.0.3\wrapper\block.go:19:17: could not determine kind of name for C.taos_fetch_raw_block

### ISSUE THREAD

**Issue by dominoTao** [taosdata/driver-go#131]
func TaosFetchRawBlock(result unsafe.Pointer) (int, int, unsafe.Pointer) {
	var cSize int
	size := unsafe.Pointer(&cSize)
	var block unsafe.Pointer
	errCode := int(C.taos_fetch_raw_block(result, (*C.int)(size), &block))
	return cSize, errCode, block
}

func TaosWriteRawBlock(conn unsafe.Pointer, numOfRows int, pData unsafe.Pointer, tableName string) int {
	cStr := C.CString(tableName)
	defer C.free(unsafe.Pointer(cStr))
	return int(C.taos_write_raw_block(conn, (C.int)(numOfRows), (*C.char)(pData), cStr))
}

i don't known what happend and how to deal with it.

**Comment by sangshuduo** [comment]
what version of TDengine you are using?

**Comment by dominoTao** [comment]
> 您使用的是什么版本的 TDengine？

3.0.1.6

**Comment by sangshuduo** [comment]
Could you please post your test code here? I will try to reproduce it.

**Comment by dominoTao** [comment]
> Could you please post your test code here? I will try to reproduce it.

i added taos.dll and taosws.dll， and then it's up and running...
