### ISSUE TITLE
part error|maxSQLLength

### ISSUE THREAD

**Issue by rexel-cn** [taosdata/driver-go#132]
go版本：1.18
td版本：2.6.0.12
driver-go版本：github.com/taosdata/driver-go/v2 v2.0.5

尝试在通过客户端配置maxSQLLength连接参数，配置格式如下：
var taosUri = fmt.Sprintf("%s:%s@tcp(%s)/log?maxSQLLength=%d", td2.User, td2.Password, td2.Url, td2.MaxSQLLength)

客户端连接程序启动之后报错：
2022-11-14T18:12:35.912+0800	ERROR	tdengine2/tdengine2.go:114	part error|maxSQLLength	{"storage": "tdengine2"}

报错所在行程序如图，供参考：
![image](https://user-images.githubusercontent.com/54128129/201637709-eb510a09-632f-4bc7-945a-145191a4259e.png)

**Comment by huskar-t** [comment]
@rexel-cn what is the value of td2.MaxSQLLength?

**Comment by rexel-cn** [comment]
@huskar-t 为配置文件中的配置参数，如下： 
 tdengine2:
    url: td-1:6030
    user: root
    password: RexelRoot
    replica: 1
    maxSQLLength: 1048576

**Comment by huskar-t** [comment]
i have tested locally and no errors appear, please print `taosUri`

**Comment by rexel-cn** [comment]
打印的url为：root:RexelRoot@tcp(td-1:6030)/log?maxSQLLength=1048576
下图为控制台日志截图：
![image](https://user-images.githubusercontent.com/54128129/201823237-aeaf6416-007b-4ff6-a2f9-ec0791042453.png)

**Comment by huskar-t** [comment]
@rexel-cn 
go 程序和 TDengine 分别运行在什么操作系统平台？看起来不像是同一台机器

**Comment by rexel-cn** [comment]
td运行环境：Ubuntu 18.04.6（docker容器）
go客户端运行环境：ubuntu 22.04（docker容器）

**Comment by huskar-t** [comment]
```
package main

import (
	"database/sql"
	"fmt"

	_ "github.com/taosdata/driver-go/v2/taosSql"
)

func main() {
	url := "root:RexelRoot@tcp(td-1:6030)/log?maxSQLLength=1048576"
	fmt.Println(url)
	db, err := sql.Open("taosSql", url)
	if err != nil {
		panic(err)
	}
	defer db.Close()
	err = db.Ping()
	if err != nil {
		panic(err)
	}
}
```
试一下上面的代码是否出错

**Comment by yu285** [comment]
可以添加下微信我们做下远程排查 ： 15652223354

**Comment by rexel-cn** [comment]
先暂时关掉了，后面继续验证的时候再确认，多谢
