### ISSUE TITLE
插入和查询数据，内存会持续增长

### ISSUE THREAD

**Issue by jinxing3114** [taosdata/driver-go#14]
下列程序运行时，内存会持续增长，上限是多少没有测试到，目前测试的结果，几百兆是已经测试到的。

> import (
	"fmt"
	log "github.com/sirupsen/logrus"
	"math/rand"
	"strconv"
	"strings"
	"time"
	"database/sql"
	_ "github.com/taosdata/driver-go/taosSql"
)

> var SQLDB *sql.DB

> func Insert(insertStr string, args ...interface{}) (int64, error) {
	result, err := SQLDB.Exec(insertStr, args...)
	if err != nil {
		return 0, err
	}
	affect, err := result.RowsAffected()
	return affect, err
}

> func Get(queryStr string, args ...interface{}) (map[string]interface{}, error) {
	rows, err := SQLDB.Query(queryStr, args...)
	if err != nil {
		if err == sql.ErrNoRows {
			return map[string]interface{}{}, nil
		}
		return map[string]interface{}{}, err
	}
	defer rows.Close()

	//将查询结果集Scan到map
	result := make([]map[string]interface{}, 0, 10)
	columns, _ := rows.Columns()
	for rows.Next() {
		value := make([]interface{}, len(columns))
		columnPointers := make([]interface{}, len(columns))
		for i := 0; i < len(columns); i++ {
			columnPointers[i] = &value[i]
		}

		rows.Scan(columnPointers...)
		data := make(map[string]interface{})
		for i := 0; i < len(columns); i++ {
			columnName := columns[i]
			columnValue := columnPointers[i].(*interface{})
			data[columnName] = *columnValue
		}
		result = append(result, data)
	}
	if len(result) > 0 {
		return result[0], nil
	}
	return nil, nil
}

> func Run() {
	user := "root"
	password := "taosdata"
	address := "127.0.0.1"
	port := 6030
	schema := "xxx"
	dataSourceName := fmt.Sprintf("%s:%s@/tcp(%s:%v)/%s", user, password, address, port, schema)
	SQLDB, _ = sql.Open("taosSql", dataSourceName)

	for {
		sqlStr := strings.Builder{}
		sqlStr.WriteString("insert into ")
		rd := make([]string, 0, 40)
		for i:=0;i<20;i++ {
			rand.Seed(time.Now().UnixNano())
			dn := strconv.FormatInt(rand.Int63(), 10)
			rid := strconv.FormatInt(rand.Int63n(1000000), 10)
			rd = append(rd, dn, rid)
			sqlStr.WriteString("xxx.t")
			sqlStr.WriteString(dn)
			sqlStr.WriteString(" using xxx.xp tags (")
			sqlStr.WriteString(dn)
			sqlStr.WriteString(",'test') ")
			sqlStr.WriteString("values (now,0,")
			sqlStr.WriteString(rid)
			sqlStr.WriteString(") ")
		}

		_, err := Insert(sqlStr.String())
		if err != nil {
			log.Errorf("error:%s\nsql:%s\n", err.Error(), sqlStr.String())
		}
		for i:=0;i<20;i+=2 {
			sql1 := `select max(time) time from xxx.xp where did = ? and run_id = ?`
			_, _ = Get(sql1, rd[i], rd[i+1])
			sql2 := `select min(time) time from xxx.xp where did = ? and run_id = ?`
			_, _ = Get(sql2, rd[i], rd[i+1])
			sql3 := `select max(run_id) run_id from xxx.xp where did = ?`
			_, _ = Get(sql3, rd[i])
		}
	}
}

使用ps找到进程ID后，通过/proc/进程ID/status看到内存使用情况

20分钟：
VmHWM:	  176440 kB
VmRSS:	  176440 kB

使用go pprof 查看程序运行情况，看到allocs 和 heap 在不断的增长

在go程序中实时获取内存使用情况，能看到自动GC垃圾回收，使用内存量不会持续增长。
var m runtime.MemStats
runtime.ReadMemStats(&m)

怀疑是调用C的类库，有内存申请但是没有释放。这部分内存go无法自动回收。

请帮忙看一下什么问题

**Comment by sangshuduo** [comment]
超级表的表结构是怎样的？

**Comment by jinxing3114** [comment]
CREATE TABLE xp (ts timestamp, xj_id int) TAGS (did bigint, model binary(30));

**Comment by jinxing3114** [comment]
@sangshuduo 客户端的内存和超级表的设计也有关系吗

**Comment by sangshuduo** [comment]
不是，是为了重现问题方便。话说 Get() 里make map 一直没有释放内存吧

**Comment by jinxing3114** [comment]
@sangshuduo 不执行get方法，内存也是一样持续增长。执行sql次数越多，内存增长速度越快，不分插入还是查询

**Comment by sangshuduo** [comment]
我试了我们官方例子 tests/examples/go/taosdemo.go 没有看到内存增长，你可以试试

**Comment by jinxing3114** [comment]
我尝试了官方例子，内存也是依旧在增长，尤其是，在插入数据的时候，增长很迅速。
运行初期：创建表过程中，内存在持续增长，内存使用增加很少。插入数据过程一开始，内存使用量猛增
我使用的参数是 go run main.go -t 10000 -n 100 -r 1000000

**Comment by sangshuduo** [comment]
表的meta data会在客户端缓存来提高性能，随着表的数量增加而增加是正常的。要看有没有内存泄露。你可以把表的数量设置少一点，比如100，在很快把表结构拉到客户端后应该会稳定，后续插入数据不应该看到内存持续增长。

**Comment by jinxing3114** [comment]
目前观测到的结果，内存确实会持续增长，而且是在插入数据的时候，增长很明显

**Comment by jinxing3114** [comment]
@sangshuduo 如果在sql中采用 insert into db.table using db.meters 这种方式自动建表，有几十万乃至几百万张表甚至更多，无法提前预创建好表，客户端运行过程中会增加的内存会持续增长，直至oom，如何保持客户端的内存使用量限制

**Comment by jinxing3114** [comment]
经过测试，如果使用预先创建好表，后续操作sql内存不会持续增长，但是采用自动建表，客户端内存会随着表的创建而增加内存。表越多，占用内存越高。

**Comment by sangshuduo** [comment]
因为预先建表是使用的时候把内存拉下来缓存到客户端机器中，用多少表拉多少表的meta data，自动建表是建的时候等于持续保存不同表的meta data，所以看到的现象不一样，而不是预先建表不增长。这个问题的解决是需要在规划的时候计算好需要多少内存，配置足够充分的物理内存或多台机器组成集群，或者把数据分区到不同的机器或集群上。否则即使是预先建表，只要客户端使用足够多的表，内存一样会爆掉。另外新版本对内存缓存做了大幅优化，可以试一下，但本质上表多了就是需要成比例的内存。

**Comment by sangshuduo** [comment]
因为预先建表是使用的时候把内存拉下来缓存到客户端机器中，用多少表拉多少表的meta data，自动建表是建的时候等于持续保存不同表的meta data，所以看到的现象不一样，而不是预先建表不增长。这个问题的解决是需要在规划的时候计算好需要多少内存，配置足够充分的物理内存或多台机器组成集群，或者把数据分区到不同的机器或集群上。否则即使是预先建表，只要客户端使用足够多的表，内存一样会爆掉。另外新版本对内存缓存做了大幅优化，可以试一下，但本质上表多了就是需要成比例的内存。
