### ISSUE TITLE
could not determine kind of name for C.taos_write_raw_block_with_fields

### ISSUE THREAD

**Issue by cmkcmk181** [taosdata/driver-go#146]
go版本：1.19
tdengin版本：3.0.1.8
driver-go版本： v3.0.4

启动时报错：
# github.com/taosdata/driver-go/v3/wrapper
D:\GOPATH\pkg\mod\github.com\taosdata\driver-go\v3@v3.0.4\wrapper\block.go:34:13: could not determine kind of name for C.taos_write_raw_block_with_fields

go原生连接：
 var taosUri = "root:taosdata@tcp(localhost:6030)/"
    taos, err := sql.Open("taosSql", taosUri)
    if err != nil {
        fmt.Println("failed to connect TDengine, err:", err)
        return
    }

**Comment by sangshuduo** [comment]
Windows 装了 TDengine 客户端吗？

**Comment by cmkcmk181** [comment]
装了

**Comment by cmkcmk181** [comment]
服务端和客户端不能装在同一电脑上吗？

**Comment by sangshuduo** [comment]
taos\_write\_raw\_block\_with\_fields 这个函数在 3.0.1.8 还没有，所以或者升级 TDengine 到最新版，或者降级 driver-go，建议升级 TDengine

**Comment by cmkcmk181** [comment]
升级了服务端到最新版本，可以连接了

**Comment by cmkcmk181** [comment]
已解决
