### ISSUE TITLE
连接池 bug 

### ISSUE THREAD

**Issue by yaobo-lab** [taosdata/driver-go#153]
测试代码：

> `  
     
       func TestTDengine(t *testing.T) {
	var taosUri = "root:taosdata@tcp(10.0.1.5:6030)/testdb?charset=utf8&interpolateParams=true&loc=Local"
	taos, err := sql.Open("taosSql", taosUri)
	if err != nil {
		fmt.Println("failed to connect TDengine, err:", err)
		return
	}

       taos.SetMaxOpenConns(5)
	taos.SetMaxIdleConns(2)

	defer taos.Close()

	for i := 0; i <50; i++ {

		go func(index int) {
			rows, err := taos.Query("select * from  t_device where appno='spider' limit 1;")

			if err != nil {
				fmt.Printf("result err:%s \n", err.Error())
			}

			rows.Close()
			fmt.Printf("test no:%d \n", index)
			time.Sleep(200 * time.Millisecond)
		}(i)
	}

	select {}
}
`
执行50次后，在部署了tdengine的集群，使用netstat 查看连接数：
10.0.3.36--->为运行测试样例的调试机器 
10.0.1.5--->为部署tdengine 3.0.2.4
netstat -antp |grep 10.0.1.5:6030 |grep 10.0.3.36

即使用调用：taos.Close() 方法连接也没有得到释放

![image](https://user-images.githubusercontent.com/21329253/219530248-72a7ae60-e520-4570-80b7-c74b4adf4b92.png)

 
![image](https://user-images.githubusercontent.com/21329253/219530516-d0ceb694-cfa3-4162-97e5-bcf5dcf694e4.png)

**Comment by sunpe** [comment]
taos.SetMaxOpenConns() 试试

**Comment by yaobo-lab** [comment]
> taos.SetMaxOpenConns() 试试

没有效果

**Comment by yaobo-lab** [comment]
发现是row 没有做释放 导致。不是库的bug

**Comment by sunpe** [comment]
请详细描述您的问题

**Comment by huskar-t** [comment]
与 taosd 6030 端口连接池由 taos.so 控制，调用 taos.Close() 不会直接关闭连接，因此不需要关心启用多少个连接到 6030。

由给出的测试代码看 `defer taos.Close()` 会在方法退出时调用，`select {}` 导致方法没有退出

**Comment by yaobo-lab** [comment]
> 与 taosd 6030 端口连接池由 taos.so 控制，调用 taos.Close() 不会直接关闭连接，因此不需要关心启用多少个连接到 6030。
> 
> 由给出的测试代码看 `defer taos.Close()` 会在方法退出时调用，`select {}` 导致方法没有退出

1. select{} 方法是为了测试：程序不退出，tcp 连接会不会释放（线程执行1000次就会有1000+个TCP 一直长连接，并且一直不释放，这样一直保持1000+个长连接的设计意义何在？）
2. 如果一直打开这么多tcp连接，不回收有何意义？程序在某一个瞬间访问量激增，然后到了晚上没有人访问，这些tcp连接也不会释放？

**Comment by yihaoDeng** [comment]
空闲连接会释放，taos_c_driver 内部有个连接池

**Comment by yaobo-lab** [comment]
> 空闲连接会释放，taos_c_driver 内部有个连接池

可以详细讲下这个释放逻辑吗？ 毕竟  生产流量也不是很大。一个节点上有1000+个 连接，

**Comment by zhouzaihang** [comment]
> > 空闲连接会释放，taos_c_driver 内部有个连接池
> 
> 可以详细讲下这个释放逻辑吗？ 毕竟 生产流量也不是很大。一个节点上有1000+个 连接，

试试走WebSocket连接？

``` go
import (
    "database/sql"
    "fmt"

    _ "github.com/taosdata/driver-go/v3/taosWS"
)
```
