### ISSUE TITLE
driver should be goroutine safe.

### ISSUE THREAD

**Issue by YiuTerran** [taosdata/driver-go#17]
>  DB is a database handle representing a pool of zero or more underlying connections.

    It's safe for concurrent use by multiple goroutines.

根据官方文档Open之后的*DB应该是可以在任意多协程使用的。这与本项目中

> 如果客户想要用多个goroutine并发访问TDengine, 那么需要在各个goroutine中分别创建一个sql.Open对象并用之访问TDengine

是矛盾的。

**Comment by zitsen** [comment]
It's save for multiple goroutines. we'll improve the documentation.

**Comment by yaobo-lab** [comment]
> > DB is a database handle representing a pool of zero or more underlying connections.
> 
> ```
> It's safe for concurrent use by multiple goroutines.
> ```
> 
> 根据官方文档Open之后的*DB应该是可以在任意多协程使用的。这与本项目中
> 
> > 如果客户想要用多个goroutine并发访问TDengine, 那么需要在各个goroutine中分别创建一个sql.Open对象并用之访问TDengine
> 
> 是矛盾的。

大佬 最后是怎样解决，多线程，并发插入，查询这种情况，连接没有得到释放的问题

**Comment by YiuTerran** [comment]
> > > DB is a database handle representing a pool of zero or more underlying connections.
> > 
> > 
> > ```
> > It's safe for concurrent use by multiple goroutines.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 根据官方文档Open之后的*DB应该是可以在任意多协程使用的。这与本项目中
> > > 如果客户想要用多个goroutine并发访问TDengine, 那么需要在各个goroutine中分别创建一个sql.Open对象并用之访问TDengine
> > 
> > 
> > 是矛盾的。
> 
> 大佬 最后是怎样解决，多线程，并发插入，查询这种情况，连接没有得到释放的问题

最后没敢用，还是用的influxdb，社区有个集群版，够用了
