### ISSUE TITLE
请问dsn连接字符串都可以设置什么参数？

### ISSUE THREAD

**Issue by feiyangbeyond** [taosdata/driver-go#186]
```go
var taosDsn = "root:taosdata@tcp(127.0.0.1:6030)/dbname" // 请问这里能加什么参数？可不可以设置格式化时间之类的参数

taos, err := sql.Open("taosSql", taosDsn)

```

因为我在插入数据时，ts字段为纳秒时间戳，查询时该字段变成字符串，

请问怎么设置查询的timestamp类型字段为int64？

**Comment by sangshuduo** [comment]
https://docs.taosdata.com/connector/go/#%E5%BB%BA%E7%AB%8B%E8%BF%9E%E6%8E%A5

https://docs.taosdata.com/taos-sql/function/#to_unixtimestamp

**Comment by feiyangbeyond** [comment]
> https://docs.taosdata.com/connector/go/#%E5%BB%BA%E7%AB%8B%E8%BF%9E%E6%8E%A5
> 
> https://docs.taosdata.com/taos-sql/function/#to_unixtimestamp

你好，to_unixtimestamp函数不能操作timestamp类型的列
