### ISSUE TITLE
invalid DSN: network address not terminated (missing closing brace)

### ISSUE THREAD

**Issue by running-db** [taosdata/driver-go#192]
1. 3.1.0.0版本，使用user:password@cfg(/etc/taos)/dbname 链接集群，执行sql报错invalid DSN: network address not terminated (missing closing brace)。把sql单独复制出来在taos客户端登录后能执行。

2. /etc/taos/taos.cfg配置保持安装客户端后的原为，并添加了“firstEp                   ch01:6030” 这一项配置，在/etc/hosts配置了ch01的解析的。

3. 程序使用user:password@tcp(host:port)/dbname这种方式链接没有问题

**Comment by sangshuduo** [comment]
修改 TDengine/examples/go/taosdemo.go 验证发现没有问题

![image](https://github.com/taosdata/driver-go/assets/825729/f6ac9f83-183c-4896-a9c3-36deb41364fd)

**Comment by running-db** [comment]
> 修改 TDengine/examples/go/taosdemo.go 验证发现没有问题
> 
> ![image](https://user-images.githubusercontent.com/825729/264519287-f6ac9f83-183c-4896-a9c3-36deb41364fd.png)

可以看看你的/etc/taos/taos.cfg不，我只添加了一行“firstEp ch01:6030”。最终插入的时候报错的，连接那个地方没报错

**Comment by sangshuduo** [comment]
你试试再加上 fqdn  ch01

**Comment by running-db** [comment]
> 你试试再加上 fqdn ch01

加上了“fqdn                      ch01”，还是一样的错误，我理解这个fqdn应该不配置ch01，这边是客户端。这个fqdn是本地机器的域名。

**Comment by running-db** [comment]
谢谢！！已经解决了，不是驱动问题，我以前在连接时多加了一个斜杠，之前一直用tcp的没有报错，这次的报错了，我按照官方的写法来没问题了。感谢你的指正
