### ISSUE TITLE
build driver-go on windows error

### ISSUE THREAD

**Issue by elihe2011** [taosdata/driver-go#30]
# 1. enviroments:
C:\TDengine\connector\go\taosSql> go env
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\msn\AppData\Local\go-build
set GOENV=C:\Users\msn\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\msn\go\pkg\mod
set GONOPROXY=github.com/go-playground/*
set GONOSUMDB=github.com/go-playground/*
set GOOS=windows
set GOPATH=C:\Users\msn\go
set GOPRIVATE=github.com/go-playground/*
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.16.3
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\TDengine\connector\go\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\msn\AppData\Local\Temp\go-build38272060=/tmp/go-build -gno-record-gcc-switches

# 2. build details:
C:\TDengine\connector\go\taosSql> go build -x
WORK=C:\Users\msn\AppData\Local\Temp\go-build3526579924
mkdir -p $WORK\b001\
cd C:\TDengine\connector\go\taosSql
TERM='dumb' CGO_LDFLAGS='"-g" "-O2" "-LC:/TDengine/driver" "-ltaos"' "c:\\go\\pkg\\tool\\windows_amd64\\cgo.exe" -objdir "$WORK\\b001\\" -importpath github.com/taosdata/driver-go/taosSql -- -I "$WORK\\b001\\" -g -O2 -IC:/TDengine/include "-IC:\\TDengine\\connector\\go\\taosSql\\usr\\include" "C:\\TDengine\\connector\\go\\taosSql\\connection.go" "C:\\TDengine\\connector\\go\\taosSql\\ctaos.go" "C:\\TDengine\\connector\\go\\taosSql\\result.go" "C:\\TDengine\\connector\\go\\taosSql\\rows.go" "C:\\TDengine\\connector\\go\\taosSql\\taosSqlCgo.go" "C:\\TDengine\\connector\\go\\taosSql\\types.go" "C:\\TDengine\\connector\\go\\taosSql\\utils.go"
cd $WORK
gcc -fno-caret-diagnostics -c -x c - -o "$WORK\\3977173656" || true
gcc -Qunused-arguments -c -x c - -o "$WORK\\737271862" || true
gcc -fdebug-prefix-map=a=b -c -x c - -o "$WORK\\3186236235" || true
gcc -gno-record-gcc-switches -c -x c - -o "$WORK\\1282230556" || true
cd $WORK\b001
TERM='dumb' gcc -I "C:\\TDengine\\connector\\go\\taosSql" -m64 -mthreads -fmessage-length=0 "-fdebug-prefix-map=$WORK\\b001=/tmp/go-build" -gno-record-gcc-switches -I "$WORK\\b001\\" -g -O2 -IC:/TDengine/include "-IC:\\TDengine\\connector\\go\\taosSql\\usr\\include" -o "$WORK\\b001\\_x001.o" -c _cgo_export.c
TERM='dumb' gcc -I "C:\\TDengine\\connector\\go\\taosSql" -m64 -mthreads -fmessage-length=0 "-fdebug-prefix-map=$WORK\\b001=/tmp/go-build" -gno-record-gcc-switches -I "$WORK\\b001\\" -g -O2 -IC:/TDengine/include "-IC:\\TDengine\\connector\\go\\taosSql\\usr\\include" -o "$WORK\\b001\\_x002.o" -c connection.cgo2.c
TERM='dumb' gcc -I "C:\\TDengine\\connector\\go\\taosSql" -m64 -mthreads -fmessage-length=0 "-fdebug-prefix-map=$WORK\\b001=/tmp/go-build" -gno-record-gcc-switches -I "$WORK\\b001\\" -g -O2 -IC:/TDengine/include "-IC:\\TDengine\\connector\\go\\taosSql\\usr\\include" -o "$WORK\\b001\\_x003.o" -c ctaos.cgo2.c
TERM='dumb' gcc -I "C:\\TDengine\\connector\\go\\taosSql" -m64 -mthreads -fmessage-length=0 "-fdebug-prefix-map=$WORK\\b001=/tmp/go-build" -gno-record-gcc-switches -I "$WORK\\b001\\" -g -O2 -IC:/TDengine/include "-IC:\\TDengine\\connector\\go\\taosSql\\usr\\include" -o "$WORK\\b001\\_x004.o" -c result.cgo2.c
TERM='dumb' gcc -I "C:\\TDengine\\connector\\go\\taosSql" -m64 -mthreads -fmessage-length=0 "-fdebug-prefix-map=$WORK\\b001=/tmp/go-build" -gno-record-gcc-switches -I "$WORK\\b001\\" -g -O2 -IC:/TDengine/include "-IC:\\TDengine\\connector\\go\\taosSql\\usr\\include" -o "$WORK\\b001\\_x005.o" -c rows.cgo2.c
TERM='dumb' gcc -I "C:\\TDengine\\connector\\go\\taosSql" -m64 -mthreads -fmessage-length=0 "-fdebug-prefix-map=$WORK\\b001=/tmp/go-build" -gno-record-gcc-switches -I "$WORK\\b001\\" -g -O2 -IC:/TDengine/include "-IC:\\TDengine\\connector\\go\\taosSql\\usr\\include" -o "$WORK\\b001\\_x006.o" -c taosSqlCgo.cgo2.c
TERM='dumb' gcc -I "C:\\TDengine\\connector\\go\\taosSql" -m64 -mthreads -fmessage-length=0 "-fdebug-prefix-map=$WORK\\b001=/tmp/go-build" -gno-record-gcc-switches -I "$WORK\\b001\\" -g -O2 -IC:/TDengine/include "-IC:\\TDengine\\connector\\go\\taosSql\\usr\\include" -o "$WORK\\b001\\_x007.o" -c types.cgo2.c
TERM='dumb' gcc -I "C:\\TDengine\\connector\\go\\taosSql" -m64 -mthreads -fmessage-length=0 "-fdebug-prefix-map=$WORK\\b001=/tmp/go-build" -gno-record-gcc-switches -I "$WORK\\b001\\" -g -O2 -IC:/TDengine/include "-IC:\\TDengine\\connector\\go\\taosSql\\usr\\include" -o "$WORK\\b001\\_x008.o" -c utils.cgo2.c
TERM='dumb' gcc -I "C:\\TDengine\\connector\\go\\taosSql" -m64 -mthreads -fmessage-length=0 "-fdebug-prefix-map=$WORK\\b001=/tmp/go-build" -gno-record-gcc-switches -I "$WORK\\b001\\" -g -O2 -IC:/TDengine/include "-IC:\\TDengine\\connector\\go\\taosSql\\usr\\include" -o "$WORK\\b001\\_cgo_main.o" -c _cgo_main.c
cd C:\TDengine\connector\go\taosSql
TERM='dumb' gcc -I "C:\\TDengine\\connector\\go\\taosSql" -m64 -mthreads -fmessage-length=0 "-fdebug-prefix-map=$WORK\\b001=/tmp/go-build" -gno-record-gcc-switches -o "$WORK\\b001\\_cgo_.o" "$WORK\\b001\\_cgo_main.o" "$WORK\\b001\\_x001.o" "$WORK\\b001\\_x002.o" "$WORK\\b001\\_x003.o" "$WORK\\b001\\_x004.o" "$WORK\\b001\\_x005.o" "$WORK\\b001\\_x006.o" "$WORK\\b001\\_x007.o" "$WORK\\b001\\_x008.o" -g -O2 -LC:/TDengine/driver -ltaos
\# github.com/taosdata/driver-go/taosSql
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: $WORK\b001\_x003.o: in function `_cgo_63e5e3757176_Cfunc_taosGetErrno':
/tmp/go-build/cgo-gcc-prolog:63: undefined reference to `taosGetErrno'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: $WORK\b001\_x003.o: in function `_cgo_63e5e3757176_Cfunc_taos_is_null':
/tmp/go-build/cgo-gcc-prolog:278: undefined reference to `taos_is_null'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: $WORK\b001\_x003.o: in function `_cgo_63e5e3757176_Cfunc_taos_stmt_is_insert':
/tmp/go-build/cgo-gcc-prolog:470: undefined reference to `taos_stmt_is_insert'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: $WORK\b001\_x003.o: in function `_cgo_63e5e3757176_Cfunc_tstrerror':
/tmp/go-build/cgo-gcc-prolog:581: undefined reference to `tstrerror'
collect2.exe: error: ld returned 1 exit status

**Comment by zitsen** [comment]
Please use branch `win`, but no stmt support.
