### ISSUE TITLE
a long insert taos_connect failed.

### ISSUE THREAD

**Issue by fengzk-edgeray** [taosdata/driver-go#42]
![image](https://user-images.githubusercontent.com/89452329/130720056-ab516fe0-703c-4005-95e4-b7d6938585c8.png)
![image](https://user-images.githubusercontent.com/89452329/130720364-d74b398e-3524-4763-856e-3922c1240539.png)
![image](https://user-images.githubusercontent.com/89452329/130597269-03cac099-305c-4f94-8281-2d43911c6fd1.png)
Background: Golang/taoSql/taos_connect fail()/long insert  taos_connect
Hello, td expert. this database was adopted to collect monitor status in our project, it inserted success but also happen many taos_connect fail()! error and 
How can I solve this problem?

**Comment by huskar-t** [comment]
@fengzk-edgeray check whether the taosd server is available, and then check whether the dsn is correct.

**Comment by huskar-t** [comment]
@fengzk-edgeray how many characters does your sql statement have?

**Comment by fengzk-edgeray** [comment]
> @fengzk-edgeray check whether the taosd server is available, and then check whether the dsn is correct.

some query insert sucesss,but some failed

**Comment by huskar-t** [comment]
> > @fengzk-edgeray check whether the taosd server is available, and then check whether the dsn is correct.
> 
> some query insert sucesss,but some failed

use a global db object and  call `db.SetMaxOpenConns(100)`
don't open database in mult goroutines
