### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by zskylark** [taosdata/driver-go#43]
环境：
go version go1.16.7 windows/amd64

gcc version 5.3.0

TDengine-client-2.0.20.13-Windows-x64.exe

使用：
import (
	"database/sql"
	"fmt"
	_ "github.com/taosdata/driver-go/taosSql"
）

编译报错：
# github.com/taosdata/driver-go/taosSql
C:\Users\XXX\AppData\Local\Temp\go-build2056628199\b167\_x003.o: In function `_cgo_3c14f7af3093_Cfunc_taosGetErrno':
/tmp/go-build/cgo-gcc-prolog:63: undefined reference to `taosGetErrno'
C:\Users\XXX\AppData\Local\Temp\go-build2056628199\b167\_x003.o: In function `_cgo_3c14f7af3093_Cfunc_taos_is_null':
/tmp/go-build/cgo-gcc-prolog:278: undefined reference to `taos_is_null'
C:\Users\XXX\AppData\Local\Temp\go-build2056628199\b167\_x003.o: In function `_cgo_3c14f7af3093_Cfunc_taos_stmt_is_insert':
/tmp/go-build/cgo-gcc-prolog:470: undefined reference to `taos_stmt_is_insert'
C:\Users\XXX\AppData\Local\Temp\go-build2056628199\b167\_x003.o: In function `_cgo_3c14f7af3093_Cfunc_tstrerror':
/tmp/go-build/cgo-gcc-prolog:581: undefined reference to `tstrerror'
collect2.exe: error: ld returned 1 exit status

Compilation finished with exit code 2

**Comment by huskar-t** [comment]
@zskylark try to use branch `win`
fix go.mod
`
require github.com/taosdata/driver-go/taosSql win
`
then execute `go mod tidy`

**Comment by zskylark** [comment]
@huskar-t it's working, thanks!
