### ISSUE TITLE
driver-go don't work well 

### ISSUE THREAD

**Issue by BestHYY** [taosdata/driver-go#46]
安装后运行测试程序报错，错误信息如下
~/go/src/github.com/taosdata/driver-go/wrapper/stmt.go:58:13: could not determine kind of name for C.taos_stmt_set_tbname
~/go/src/github.com/taosdata/driver-go/wrapper/stmt.go:39:14: could not determine kind of name for C.taos_stmt_set_tbname_tags

libtaos.so已存在，版本为2.2.0.0，具体位置和链接信息下
```
root@localhost:/usr/lib# ll |grep libtaos.so
lrwxrwxrwx  1 root root      27 Sep  9 18:51 libtaos.so -> /usr/local/lib/libtaos.so.1*
root@localhost:/usr/lib# cd /usr/local/lib
root@localhost:/usr/local/lib# ll|grep libtaos.so
lrwxrwxrwx  1 root root        12 Jul 27 10:41 libtaos.so -> libtaos.so.1*
lrwxrwxrwx  1 root root        33 Sep  9 14:57 libtaos.so.1 -> /usr/local/lib/libtaos.so.2.2.0.0*
-rwxr-xr-x  1 root root   8340544 Jul 27 10:41 libtaos.so.2.0.20.10*
-rwxr-xr-x  1 root root  10280216 Sep  9 14:57 libtaos.so.2.2.0.0*
root@localhost:/usr/local/lib#
```

**Comment by huskar-t** [comment]
@BestHYY  please check that the version of taos.h is 2.2.0.0 instead of 2.0.20.10.
default path is `/usr/include/taos.h`

**Comment by huskar-t** [comment]
@BestHYY looking forward to your reply.

**Comment by BestHYY** [comment]
问题已解决，我之前的taos.h版本是2.0的，多谢
