### ISSUE TITLE
AGPL协议？

### ISSUE THREAD

**Issue by kooksee** [taosdata/driver-go#53]
1. 我看到咱们产品都是使用AGPL这种协议的，感觉这种协议限制性太大了吧
2. 使用了就要开源，那公司就没办法使用了啊

**Comment by sangshuduo** [comment]
1. 不能用来提供云服务
2. 只要求开源修改过的 TDengine 代码，只是使用没问题

**Comment by kooksee** [comment]
@sangshuduo 
你说的，我明白，但是，如果只是使用了`driver-go`, 这个库的情况下，就没必要开源了吧？

一般通过driver-go构建的是独立的程序，和TDengine进行通信，不受GPL感染。但是，如果这个库都是GPL了，那还怎么用啊？

**Comment by sangshuduo** [comment]
> @sangshuduo 你说的，我明白，但是，如果只是使用了`driver-go`, 这个库的情况下，就没必要开源了吧？
> 
> 一般通过driver-go构建的是独立的程序，和TDengine进行通信，不受GPL感染。但是，如果这个库都是GPL了，那还怎么用啊？

这里用 AGPL 确实不太合理，之前代码和 TDengine 在一个仓库，后来分开成单独仓库没有考虑这一点。我们内部在讨论改为宽松许可。你可以先用起来。

**Comment by kooksee** [comment]
嗯嗯，好的，感谢感谢。
