### ISSUE TITLE
won't work with server version v1.6.6.1

### ISSUE THREAD

**Issue by genelet** [taosdata/driver-go#6]
golang/src/github.com/taosdata/driver-go/taosSql/result.go:45:11: could not determine kind of name for C.taos_use_result

But it works with v1.6.5.1

**Comment by liu0x54** [comment]
the reason is that the code in the master branch is adapted to TDengine 1.6.x, the develop branch  matches the TDengine develop branch. Now the master branch is switched  and you can try it again

**Comment by xiddjp** [comment]
use taos-1.6.3.1-linux-2019-11-07-11-17 still exist this issue.
@liu0x54 how to resolve this issue?

**Comment by sangshuduo** [comment]
@xiddjp pls use latest 2.x version. we don't maintain version 1.x any more.

**Comment by xiddjp** [comment]
@sangshuduo OMG, but 2.x version can not run taos：
taos connect failed, reason: Unable to establish connection.

**Comment by sangshuduo** [comment]
@xiddjp  you need fully upgrade all components to 2.x and make sure using same version client to connect same version server.
