### ISSUE TITLE
请问下TDengine的RESTFul api支持类型prepared statement的查询方式吗

### ISSUE THREAD

**Issue by wenj91** [taosdata/driver-go#61]
比如说我用RESTFul api如何实现类似：select * from tb1 where a = ?;

**Comment by sangshuduo** [comment]
这个问题不是特定 go connector 的吧？是不是应该提在 https://github.com/taosdata/TDengine 的 issue 下？

**Comment by wenj91** [comment]
> 这个问题不是特定 go connector 的吧？是不是应该提在 https://github.com/taosdata/TDengine 的 issue 下？

因为我想用RESTFul的api重新封装一个纯golang的驱动，所以想在这里像你们咨询下你们是否知道这个情况

**Comment by sangshuduo** [comment]
> > 这个问题不是特定 go connector 的吧？是不是应该提在 https://github.com/taosdata/TDengine 的 issue 下？
> 
> 因为我想用RESTFul的api重新封装一个纯golang的驱动，所以想在这里像你们咨询下你们是否知道这个情况

目前不支持

**Comment by wenj91** [comment]
不好意思，我还是把这个issue关闭了吧，我去java的驱动看下实现的细节，看下java那边是怎么处理的

**Comment by wenj91** [comment]
> 不好意思，我还是把这个issue关闭了吧，我去java的驱动看下实现的细节，看下java那边是怎么处理的

看了下java那边的实现，是通过驱动层自行解析sql语句最终拼接好sql然后再执行的
