### ISSUE TITLE
使用golang客户端报错

### ISSUE THREAD

**Issue by xiao9878** [taosdata/driver-go#66]
使用[dirver-go](https://github.com/taosdata/driver-go)的样例代码进行测试，无法通过编译，报错如下：
```go
# github.com/taosdata/driver-go/v2/wrapper
D:\Develop\go\pkg\mod\github.com\taosdata\driver-go\v2@v2.0.0\wrapper\field.go:4:10: fatal error: taos.h: No such file or directory
 #include <taos.h>
          ^~~~~~~~
compilation terminated.
```
环境是：Windows11 go版本为：1.17.3
使用mac编译也是相同的报错

**Comment by sangshuduo** [comment]
需要按照 TDengine server 或 TDengine client 安装包，或者自己源码编译 TDengine 并安装

**Comment by xiao9878** [comment]
![image](https://user-images.githubusercontent.com/52389309/147197520-d1819b19-7a74-4c13-b25a-9b1e9d5028f8.png)
安装也会报这样的错，需要用客户端的主机在此之前需要做什么准备工作吗

**Comment by sangshuduo** [comment]
参考： https://github.com/taosdata/driver-go/issues/43

**Comment by xiao9878** [comment]
![image](https://user-images.githubusercontent.com/52389309/147199659-657b395f-280e-4220-902e-66f668c75b4a.png)
emmm...尝试使用win分支也是相同的报错

**Comment by xiao9878** [comment]
不好意思，之前没下驱动...问题解决了
