### ISSUE TITLE
使用go api（根据该driver-test改的）创建表，但是实际没有，到insert数据时也很慢

### ISSUE THREAD

**Issue by running-db** [taosdata/driver-go#7]
func CreateTables(db *sql.DB, numOfSubTab int) {
	db.Exec("drop table if exists super")
	db.Exec("CREATE TABLE super (ts timestamp, value BOOL) tags (degress int)")
	for i := 0; i < numOfSubTab; i++ {
		db.Exec(fmt.Sprintf("create table t%d using super tags(%d)", i%10, i))
	}
}

func InsertInto(db *sql.DB, numOfSubTab, numOfItems int) {
	now := time.Now()
	t := now.Add(-100 * time.Hour)
	for i := 0; i < numOfItems; i++ {
		db.Exec(fmt.Sprintf("insert into t%d values(%d, %t)", i%numOfSubTab, t.UnixNano()/int64(time.Millisecond)+int64(i), i%2 == 0))
	}
}

执行时发现没报错，但是数据库没有创建表，insert也执行很慢;
后来在客户端上的hosts文件中配置上服务器的fqdn后就正常了

后来抓包发现mnode返回的节点信息中使用的是fqdn，客户端再次访问需要解析。

我的疑问是这种情况，解析不出来这个机器，是否应该报错，实际是没报错，然后表也没创建成功

**Comment by sangshuduo** [comment]
请参考一下 https://github.com/taosdata/TDengine/blob/develop/tests/examples/go/taosdemo.go
