### ISSUE TITLE
在windows下编译linux可执行程序报错

### ISSUE THREAD

**Issue by Alsmile** [taosdata/driver-go#71]
用 mingw64 或 cmd设置set GOOS=linux，编译可执行程序报错：
imports github.com/taosdata/driver-go/v2/taosSql
imports github.com/taosdata/driver-go/v2/wrapper: build constraints exclude all Go files in 
  work\go\pkg\mod\github.com\taosdata\driver-go\v2@v2.0.0\wrapper

**Comment by huskar-t** [comment]
@Alsmile 由于使用 cgo 所以无法跨平台编译，请在 linux 环境中编译

**Comment by Alsmile** [comment]
我知道，后面会不会有解决方法。只能在公司服务器上编译稍显麻烦，比如出差

**Comment by huskar-t** [comment]
@Alsmile 可以使用 windows 的 ubuntu 子系统或者使用虚拟机
