### ISSUE TITLE
在程序中无法使用的sql，反而在taos client中执行成功了

### ISSUE THREAD

**Issue by Harry-xu** [taosdata/driver-go#75]
![image](https://user-images.githubusercontent.com/30856770/155307442-b00e5755-e259-4dcd-b557-046a9a3c4fe6.png)
这是我程序打印的sql语句，执行结果

![image](https://user-images.githubusercontent.com/30856770/155307669-a8d438a6-ef97-4c16-a596-7ab2c76231a8.png)
这个是linux中的taos client执行的结果

td版本：2.2.2.10
driver-go版本：v2.0.0

疑惑：为何程序中执行的是失败的，而linux中taos client却是成功的

**Comment by huskar-t** [comment]
@Harry-xu 能提供一个的 golang 样本吗

**Comment by huskar-t** [comment]
@Harry-xu golang 的运行环境是 linux 还是 windows

**Comment by Harry-xu** [comment]
> @Harry-xu golang 的运行环境是 linux 还是 windows

运行环境在windows上，以下是golang insert的代码
`package test

import (
	"context"
	"database/sql"
	"fmt"
	_ "github.com/taosdata/driver-go/v2/taosSql"
	"testing"
	"time"
)

const (
	user = "root"
	pass = "taosdata"
	ip = "139.xxx.xxx.xx"
	port = "6030"
	dbname = "xxxxx"
	driverName = "taosSql"
	max_idle_conns = 10
	max_open_conns = 100
	conn_max_lifetime = 60
	conn_max_idletime = 60
)

// 连接td
func connect() (*sql.DB, error) {
	var driver = fmt.Sprintf("%s:%s/tcp(%s:%v)/%s", user, pass, ip, port, dbname)
	//
	conn, err := sql.Open(driverName, driver)
	if err != nil {
		return nil, err
	}

	conn.SetMaxIdleConns(max_idle_conns)
	conn.SetMaxOpenConns(max_open_conns)
	conn.SetConnMaxIdleTime(conn_max_lifetime * time.Second)
	conn.SetConnMaxLifetime(conn_max_idletime * time.Second)
	return conn, nil
}

func TestInsertWarn(t *testing.T) {
	db, err := connect()
	if err != nil {
		t.Log(err)
		return
	}

	sql := "INSERT INTO warn_73e30ac9e8fe48a283e82b12e6dfe4 USING system_warn TAGS ('73e30ac9e8fe48a283e82b12e6dfe4', '2222') VALUES (1645614107254, '73e30ac9e8fe48a283e82b12e6dfe4', '1234567890', 0, 1641522211203, 1641522211203, '2222', '超速行驶', 1, 12.87909099, 120.98789600, 80.09898000, 130.09878979)"
	_, err = db.ExecContext(context.Background(), sql)
	if err != nil {
		t.Log(err)
		return
	}
	t.Log("insert success")
}

`

**Comment by Harry-xu** [comment]
我将sql 语句更改加了转义 还是相同的错误  
 invalid operation: '超速行驶' (Invalid argument)
`sql := "INSERT INTO warn_73e30ac9e8fe48a283e82b12e6dfe4 USING system_warn TAGS ('73e30ac9e8fe48a283e82b12e6dfe4', '2222') VALUES (1645614107254, '73e30ac9e8fe48a283e82b12e6dfe4', '1234567890', 0, 1641522211203, 1641522211203, '2222', \"超速行驶\", 1, 12.87909099, 120.98789600, 80.09898000, 130.09878979)"`

**Comment by afwerar** [comment]
我这边在2.2.2.10试了一下都是能成功插入的，用转义也是可以的。你window上taos.cfg里locale、charset有什么特殊配置吗

**Comment by afwerar** [comment]
windows上的taos.dll也是2.2.2.10版本的吧

**Comment by Harry-xu** [comment]
> 我这边在2.2.2.10试了一下都是能成功插入的，用转义也是可以的。你window上taos.cfg里locale、charset有什么特殊配置吗

# system locale
# locale                en_US.UTF-8

# default system charset
# charset               UTF-8

这个是我taos.cfg里的配置，什么都没有动

taos.dll也是2.2.2.10版本的

`sql := "INSERT INTO warn_73e30ac9e8fe48a283e82b12e6dfe4 USING system_warn TAGS ('73e30ac9e8fe48a283e82b12e6dfe4', '2222') VALUES (1645614107254, '73e30ac9e8fe48a283e82b12e6dfe4', '1234567890', 0, 1641522211203, 1641522211203, '2222', \"超速行驶\", 1, 12.87909099, 120.98789600, 80.09898000, 130.09878979)"`
1. 这条语句中的 超速行驶，换成英文，就可以插入
2. 使用中文转义就会从 "" 变成 ''， 不明白这个是什么原因

**Comment by Harry-xu** [comment]
> 我这边在2.2.2.10试了一下都是能成功插入的，用转义也是可以的。你window上taos.cfg里locale、charset有什么特殊配置吗

# system locale
# locale                en_US.UTF-8

# default system charset
# charset               UTF-8

这个是我taos.cfg里的配置，什么都没有动

taos.dll也是2.2.2.10版本的

`sql := "INSERT INTO warn_73e30ac9e8fe48a283e82b12e6dfe4 USING system_warn TAGS ('73e30ac9e8fe48a283e82b12e6dfe4', '2222') VALUES (1645614107254, '73e30ac9e8fe48a283e82b12e6dfe4', '1234567890', 0, 1641522211203, 1641522211203, '2222', \"超速行驶\", 1, 12.87909099, 120.98789600, 80.09898000, 130.09878979)"`
1. 这条语句中的 超速行驶，换成英文，就可以插入
2. 使用中文转义就会从 "" 变成 ''， 不明白这个是什么原因

**Comment by Harry-xu** [comment]
> 我这边在2.2.2.10试了一下都是能成功插入的，用转义也是可以的。你window上taos.cfg里locale、charset有什么特殊配置吗

`# system locale
# locale                en_US.UTF-8

# default system charset
# charset               UTF-8`

这个是我taos.cfg里的配置，什么都没有动

taos.dll也是2.2.2.10版本的

`sql := "INSERT INTO warn_73e30ac9e8fe48a283e82b12e6dfe4 USING system_warn TAGS ('73e30ac9e8fe48a283e82b12e6dfe4', '2222') VALUES (1645614107254, '73e30ac9e8fe48a283e82b12e6dfe4', '1234567890', 0, 1641522211203, 1641522211203, '2222', \"超速行驶\", 1, 12.87909099, 120.98789600, 80.09898000, 130.09878979)"`

1. 这条语句中的 超速行驶，换成英文，就可以插入
2. 使用中文转义就会从 "" 变成 ''， 不明白这个是什么原因

**Comment by afwerar** [comment]
你加我微信吧，微信号afwerar
