### ISSUE TITLE
insert test data  return [0x15] err

### ISSUE THREAD

**Issue by exuan** [taosdata/driver-go#76]
```
var taosuri = "root:taosdata/tcp(10.233.65.65:6030)/"
s, err := sql.Open("taosSql", taosuri)

if err != nil {
fmt.Errorf("failed to connect TDengine, err:%v", err)
return nil, nil, err
}
fmt.Println(s.Ping())
fmt.Println(s.Exec(`insert into test.tb1 values(now+1s, 2)`))
```

```
数据库名:  test
创建时间:  2022-03-01 00:56:00.249
可更新:  否
cache(MB):  16
cachelast:  0
comp:  2
days:  10
fsync:  3000
keep0,keep1,keep(D):  undefined
maxrows:  4096
minrows:  100
ntables:  1
quorum:  1
replica:  1
status:  ready
vgroups:  1
wallevel:  1
precision:  ms
```

**Comment by huskar-t** [comment]
@exuan 
[0x15] Unable to resolve FQDN.
Reference：

- https://www.taosdata.com/docs/cn/v2.0/faq#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E5%88%97%E8%A1%A8
- https://www.taosdata.com/2020/09/11/1824.html

**Comment by exuan** [comment]
> @exuan [0x15] Unable to resolve FQDN. Reference：
> 
>     * https://www.taosdata.com/docs/cn/v2.0/faq#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E5%88%97%E8%A1%A8
> 
>     * https://www.taosdata.com/2020/09/11/1824.html

thx. but, I don't agree with using FQDN
