### ISSUE TITLE
重新订阅数据不会从上次结束的地方开始

### ISSUE THREAD

**Issue by watjt** [taosdata/driver-go#79]
https://github.com/taosdata/driver-go/blob/5afdb16902d507064deb79a5c0b87d7c9ef6ff3d/af/conn_test.go#L67  我使用这个测试案例，在中间增加了unsubscribe(true)后重新订阅，发现也是不会从上次结束的地方开始，这是什么原因？
![1647595694(1)](https://user-images.githubusercontent.com/38395110/158976899-7e84c85d-1087-4cfb-80fe-22a63633c782.png)
![1647595740(1)](https://user-images.githubusercontent.com/38395110/158977012-22373de3-b618-4586-93d1-d44eaab66388.png)

**Comment by huskar-t** [comment]
@watjt 
set the restart parameter to false on the second call to Subscribe
`subscriber, err = db.Subscribe(false, "test_subscribe", sql, time.Second*1)`
