### ISSUE TITLE
taosRestful  并发出错

### ISSUE THREAD

**Issue by yanni-coffee** [taosdata/driver-go#84]
"error": "Post \"http://root:***@127.0.0.1:6041/rest/sqlutc\": write tcp 127.0.0.1:50354->127.0.0.1:6041: use of closed network connection"}

taosd : 2.4.0.0

单线程执行正常， 改为 goroutine 并发执行时报上面的错.

执行方式改为：   _ "github.com/taosdata/driver-go/v2/taosSql" 

10个并发一切正常。

**Comment by huskar-t** [comment]
@yanni-coffee 请提供失败用例
