### ISSUE TITLE
根据 examples 文件内的例子，订阅数据每次都会重新拉取所有数据一次。是否需要在客户端配置什么吗？

### ISSUE THREAD

**Issue by nicett** [taosdata/driver-go#86]
```
topic.Unsubscribe(true)

topic, err := db.Subscribe(false, "taoslogtail", "select ts, level, ipaddr, content from log", time.Second)
```

**Comment by huskar-t** [comment]
@nicett 请给出测试代码并给出系统环境和 TDengine 版本

**Comment by nicett** [comment]
@huskar-t  已经咨询过你们技术人员，是因为客户端没有自动创建 /var/lib/taos/subscribe 这个文件夹造成的问题 
不过文档里没有提到 客户端 这个配置项在哪里
也没有自动生成 
我的环境是 docker 容器 镜像 golang:latest  1.18
TD客户端版本 version: 2.4.0.16
TD服务端版本 version: 2.4.0.16
测试代码：  [taosdata/driver-go/examples/taoslogtail/taoslogtail.go](https://github.com/taosdata/driver-go/blob/master/examples/taoslogtail/taoslogtail.go)

**Comment by huskar-t** [comment]
·
